### ISSUE TITLE
MathCaptchaWidget broken in Django 1.11

### ISSUE THREAD

**Issue by laurendw** [alsoicode/django-simple-math-captcha#11]
Django 1.11 implemented templates for widgets, and Widget.format_output() was removed. See https://docs.djangoproject.com/en/1.11/releases/1.11/ for more details. 

I took a look at it, but it was a little more complicated to fix than I anticipated.

**Comment by alsoicode** [comment]
Thanks for the report. I'll have a look as soon as I can for you.

**Comment by alsoicode** [comment]
@laurendw My apologies for not being able to get to this yet. It's been a busy week. Hopefully my schedule will let up a bit and I get to this soon. Pull requests are always welcome ;)

**Comment by laurendw** [comment]
@alsoicode I spent last weekend trying to figure out enough about how the code worked, and what the changes all mean, with the goal of sending you the issue + PR, but ran out of time to figure it all out. I'll try to take another look this weekend (too busy before then), but would appreciate any help figuring things out (such as how to find the template; I tried a number of potential directories and none of them worked).

**Comment by alsoicode** [comment]
I *should* have some time to take a look before the weekend. Hopefully it's
not a showstopper for you.

**Comment by laurendw** [comment]
It isn't a showstopper; I just took it off for now and am relying on the honeypot I also implemented. Fortunately my site apparently isn't  a spam magnet. Thanks!

**Comment by alsoicode** [comment]
Ok great - I hate when I'm the showstopper :)

**Comment by ajrbyers** [comment]
Would love a fix for this, just noticed that its broken on my live site >.<

**Comment by alsoicode** [comment]
Hi all,

My apologies for the delay getting this fixed. I have been insanely busy
both at work and at home. I would greatly welcome some assistance with
getting this widget updated.

Brandon

**Comment by kscottj** [comment]
Here is how I fixed it(widget.py):

    def format_output(self, rendered_widgets):
        #KJs MOD FOR DJANGO 1.11 this is actually a list
        htmlSnipit =  '%s %s %s' %(self.question_html,rendered_widgets[0],rendered_widgets[1] )
      
        return mark_safe(htmlSnipit)

    def render(self, name, value, attrs=None):
    
        # hash answer and set as the hidden value of form
        hashed_answer = self.generate_captcha()
        value = ['', hashed_answer]
        #KJs MOD FOR DJANGO 1.11
        widgets=super(MathCaptchaWidget, self).render(name, value, attrs=attrs)

        return widgets

**Comment by kscottj** [comment]
The above fix actually only works in v1.9  :-(

**Comment by alsoicode** [comment]
@kscottj I'm getting unit test errors with your changes. Install: requirements/test.txt then run: runtests.py

**Comment by kscottj** [comment]
The test is running for me, but, I am running against Django v1.9(This is what Google appengine uses) under virtualenv.

Using this revised code:

    def format_python(self, rendered_widgets):
        #KJs MOD FOR DJANGO 1.9-10 this is actually a list
        htmlSnipit =  '%s %s %s' %(self.question_html,rendered_widgets[0],rendered_widgets[1] )
        return mark_safe(htmlSnipit)

    def format_output(self, rendered_widgets):
        #KJs MOD FOR DJANGO 1.9 - 1.10 this is actually a list
        return self.format_python(rendered_widgets)     
        
    def render(self, name, value, attrs=None):
    
        # hash answer and set as the hidden value of form
        hashed_answer = self.generate_captcha()
        value = ['', hashed_answer]
        #KJs MOD FOR DJANGO 1.9-10
        widgets=super(MathCaptchaWidget, self).render(name, value, attrs=attrs)

        return widgets

Obviously it does not run under 1.11 :-(

**Comment by alsoicode** [comment]
Ah. Sorry, I somehow missed the 1.9 part; guess my coffee was still processing at the time.

I'm not sure what's up with 1.11. I'm right in the middle of a very large Django / Angular 5 project at the moment, and it may be a while until I can get back to this. If you want to make a pull request for your 1.9 compatible code, I can create a release for you until the 1.11 compatible version is done.

**Comment by klimanek** [comment]
Just managed to update all codes in my Django projects to be compatible with the 1.11 release. And then I found out the captcha was broken. Hack. Anyone progressed with it?

**Comment by alsoicode** [comment]
Evening everyone. My apologies for the state of this code. I literally haven't had a chance to touch it in months. Additional maintainers would be greatly appreciated.

**Comment by dnelson86** [comment]
Well, it's not elegant, but a working fix:

1. In `widgets.py` add at the very top of the class:

```
class MathCaptchaWidget(forms.MultiWidget):
    template_name = 'simplemathcaptcha/form.html'
```

2. delete `format_output()` and add instead:

```
    def get_context(self, name, value, attrs):
        attrs['question_html'] = self.question_html
        return super(MathCaptchaWidget, self).get_context(name, value, attrs)
```

3. make a new file under the path `templates/simplemathcaptcha/form.html` with the contents:

```
{{widget.attrs.question_html}}
{% for widget in widget.subwidgets %}
<input type="{{ widget.type }}" name="{{ widget.name }}"{% if widget.value != None %} value="{{ widget.value|stringformat:'s' }}"{% endif %}{% for name, valu
e in widget.attrs.items %}{% if value is not False %}{% ifnotequal name 'question_html' %} {{ name }}{% if value is not True %}="{{ value|stringformat:'s' }}
"{% endif %}{% endifnotequal %}{% endif %}{% endfor %} />
{% endfor %}
```

If someone could clean it up and incorporate it into the repo that would be great.

**Comment by alsoicode** [comment]
@dnelson86 version 1.0.8 has fixes for Django 2. Please let me know if it fixes your issue.
