### ISSUE TITLE
Does not show the problem in Django 2.1

### ISSUE THREAD

**Issue by fdik** [alsoicode/django-simple-math-captcha#12]
Hi,

tested it in Django 2.1 by adding it to a form. It's showing the label of the field and a text field – but the problem text is missing, rendering it unusable.

Is there a way to show the problem text, too? Or is this an incompatibility with Django 2?

Yours,
VB.

**Comment by alsoicode** [comment]
Morning,

I haven't had time to maintain this package in quite a while. I'm not sure when I would have time to look at fixing this, but if you need a solution that works today, I'd suggest going with reCaptcha.

Kindest regards,
Brandon

**Comment by fdik** [comment]
Hi, Brandon,

unfortunately, reCaptcha is no option because of privacy concerns. I'll have a look onto the code myself in this case.

Yours,
VB.

**Comment by alsoicode** [comment]
Hi @fdik version 1.0.8 is now available on PyPi and should fix Django 2 issues.
