### ISSUE TITLE
Six is required to use this with Django 3.x

### ISSUE THREAD

**Issue by RidenShark** [alsoicode/django-simple-math-captcha#18]
Can python 2 support be dropped already?

**Comment by alsoicode** [comment]
@RidenShark pull requests are always welcome. I'm ok with dropping Python 2.

**Comment by rustamzh** [comment]
@alsoicode hi. I have forked the repo and have adjusted the supported version of Python and Django based on their own support (Python >=3.5, Django >=2.2). Would you like a PR with these changes?

**Comment by alsoicode** [comment]
@rustamzh My apologies for the late reply, this completely fell off my radar. Yes please send me a pull request.
