### ISSUE TITLE
Please publish a release (for Django 3.x or later)

### ISSUE THREAD

**Issue by sumpfralle** [alsoicode/django-simple-math-captcha#20]
The recent releases of Django (since 3.0) do not work anymore with `django-simple-math-captcha`, since it dropped its python2 compatibility features (e.g. `django.utils.six`).

The current state of the `django-simple-math-captcha` repository seems to have fixed all related issues, thus it would be great, if you could tag a release.

Thanks!

**Comment by alsoicode** [comment]
Hello. Sorry for the delay getting back to you. I have released the latest code as version 1.1.0 to PyPi.

**Comment by sumpfralle** [comment]
Hehe - that was quick :)
Thank you!
