### ISSUE TITLE
There is  a compatibility issue in Django 4.0 (cannot import name 'ugettext_lazy' from 'django.utils.translation')

### ISSUE THREAD

**Issue by jankrnavek** [alsoicode/django-simple-math-captcha#21]
There is a compatibility issue in Django 4.0 (cannot import name 'ugettext_lazy' from 'django.utils.translation').

Please change in the file **simplemathcaptcha/fields.py**:
from django.utils.translation import **ugettext_lazy**-> from django.utils.translation import **gettext_lazy**

Thank you.
H.

**Comment by alsoicode** [comment]
My apologies for the slow reply, I've been extremely busy with work. I'll see if I can get a new release out soon. Pull requests are always welcome.

**Comment by alsoicode** [comment]
@jankrnavek So sorry this took soooo long to get out, but version 2.0.0 is available on PyPi.
